runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: 'dataadder'
  MYSQL_PASSWORD: '12345'
  MYSQL_DB: 'test'
  MYSQL_HOST: '34.133.0.108'

handlers:
- url: /script
  static_dir: static/script
- url: /styles
  static_dir: static/styles
